language: python
env:
  - DJANGO_VERSION=2.0.3
install:
  - python setup.py -q install
python:
  - "3.6.4"
# command to install dependencies
install:
  - pip install pyyaml
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install coveralls
script:
  - python manage.py test
  - coverage run --source='.' manage.py test
  - python manage.py makemigrations index
  - python manage.py migrate
after_success: coveralls
